- hosts: localhost
  gather_facts: False

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-0323c3dd2da7fb37d  # Amazon Linux
      keypair: baistonprod # pem file name
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-7731cd56
         assign_public_ip: yes
      register: ec2
